services:

  - type: web
    name: parksense-dashboard
    runtime: node

    rootDir: dashboard

    buildCommand: npm install
    startCommand: node server.js

    envVars:

      - key: SENSOR_API_URL

        fromService:
          type: web
          name: parksense-sensor
          envVarKey: RENDER_EXTERNAL_URL

      - key: ALLOCATION_API_URL

        fromService:
          type: web
          name: parksense-allocation
          envVarKey: RENDER_EXTERNAL_URL

      - key: ANALYTICS_API_URL

        fromService:
          type: web
          name: parksense-analytics
          envVarKey: RENDER_EXTERNAL_URL

      - key: NOTIFICATION_API_URL

        fromService:
          type: web
          name: parksense-notification
          envVarKey: RENDER_EXTERNAL_URL


  - type: web
    name: parksense-sensor
    runtime: node

    rootDir: services/sensor-service

    buildCommand: npm install
    startCommand: node server.js

    envVars:

      - key: DATABASE_URL

        fromDatabase:
          name: parksense-db
          property: connectionString

      - key: NODE_ENV
        value: production


  - type: web
    name: parksense-allocation
    runtime: node

    rootDir: services/parking-allocation-service

    buildCommand: npm install
    startCommand: node server.js

    envVars:

      - key: DATABASE_URL

        fromDatabase:
          name: parksense-db
          property: connectionString

      - key: NODE_ENV
        value: production


  - type: web
    name: parksense-notification
    runtime: node

    rootDir: services/notification-service

    buildCommand: npm install
    startCommand: node server.js

    envVars:

      - key: NODE_ENV
        value: production


  - type: web
    name: parksense-analytics
    runtime: node

    rootDir: services/analytics-service

    buildCommand: npm install
    startCommand: node server.js

    envVars:

      - key: DATABASE_URL

        fromDatabase:
          name: parksense-db
          property: connectionString

      - key: NODE_ENV
        value: production


databases:

  - name: parksense-db

    databaseName: smart_parking

    user: parksense